title: Floris de Vries - Software Engineer & Solution Architect
description: Professional Software Engineering and Solution Architecture Services
sitename: Floris de Vries - Software Engineer
author: Floris de Vries
logo: assets/images/pf.jpg
banner: assets/images/banner.jpg
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  projects:
    output: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
kramdown:
  parse_block_html: true
